[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
fuzz = { runs = 256 }
optimizer = true
optimizer_runs = 200
remappings = [
  '@openzeppelin/=node_modules/@openzeppelin/',
]
block_number = 16826654
block_timestamp = 1678803642

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[profile.ci]
no_match_test = "testSim"
fuzz = { runs = 5_000, max_test_rejects = 1000000 }

[profile.sim]
match_test = "testSim"
fuzz = { runs = 5_000, max_test_rejects = 1000000 }

[fmt]
ignore = ["src/libraries/LibClone.sol", "src/utils/Clone.sol", "src/libraries/ABDKMathQuad.sol"]
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
override_spacing = false
quote_style = "double"
tab_width = 4
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[invariant]
runs = 50
depth = 500
fail_on_revert = true